---
deployment:
  tasks:
    - export DEPLOYPATH=/home/vcf5s8pn1hj9/public_html/
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R Source $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp batches.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp careers.html $DEPLOYPATH
    - /bin/cp membership.html $DEPLOYPATH
    - /bin/cp nutrition.html $DEPLOYPATH
    - /bin/cp training.html $DEPLOYPATH